CREATE TABLE db_tp1.historial_ediciones_asistencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asistencia_sesion_id BIGINT NOT NULL REFERENCES db_tp1.asistencias_sesion(id),
    estado_anterior VARCHAR(20),
    estado_nuevo VARCHAR(20) NOT NULL,
    observacion_anterior VARCHAR(255),
    observacion_nueva VARCHAR(255),
    motivo VARCHAR(500) NOT NULL,
    usuario_editor_id BIGINT NOT NULL REFERENCES db_tp1.usuarios(id),
    fecha_edicion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_historial_asistencia_sesion
    ON db_tp1.historial_ediciones_asistencia (asistencia_sesion_id, fecha_edicion DESC);
